
PH_CITIES_MUNICIPALITIES = {
    'Abulug': ['MUNICIPALITY', 'Philippines'],
    'Adams': ['MUNICIPALITY', 'Philippines'],
    'Agno': ['MUNICIPALITY', 'Philippines'],
    'Aguilar': ['MUNICIPALITY', 'Philippines'],
    'Agoo': ['MUNICIPALITY', 'Philippines'],
    'Alcala': ['MUNICIPALITY', 'Philippines'],
    'Alilem': ['MUNICIPALITY', 'Philippines'],
    'Allacapan': ['MUNICIPALITY', 'Philippines'],
    'Aloguinsan': ['MUNICIPALITY', 'Philippines'],
    'Altavas': ['MUNICIPALITY', 'Philippines'],
    'Amulung': ['MUNICIPALITY', 'Philippines'],
    'Anao': ['MUNICIPALITY', 'Philippines'],
    'Angadanan': ['MUNICIPALITY', 'Philippines'],
    'Angono': ['MUNICIPALITY', 'Philippines'],
    'Anilao': ['MUNICIPALITY', 'Philippines'],
    'Antipas': ['MUNICIPALITY', 'Philippines'],
    'Aparri': ['MUNICIPALITY', 'Philippines'],
    'Arakan': ['MUNICIPALITY', 'Philippines'],
    'Arayat': ['MUNICIPALITY', 'Philippines'],
    'Aringay': ['MUNICIPALITY', 'Philippines'],
    'Badoc': ['MUNICIPALITY', 'Philippines'],
    'Bagabag': ['MUNICIPALITY', 'Philippines'],
    'Bago': ['CITY', 'Philippines'],
    'Baguio': ['CITY', 'Philippines'],
    'Bacarra': ['MUNICIPALITY', 'Philippines'],
    'Bacnotan': ['MUNICIPALITY', 'Philippines'],
    'Bacoor': ['CITY', 'Philippines'],
    'Badian': ['MUNICIPALITY', 'Philippines'],
    'Badiangan': ['MUNICIPALITY', 'Philippines'],
    'Badoc': ['MUNICIPALITY', 'Philippines'],
    'Baggao': ['MUNICIPALITY', 'Philippines'],
    'Balabac': ['MUNICIPALITY', 'Philippines'],
    'Balagtas': ['MUNICIPALITY', 'Philippines'],
    'Balasan': ['MUNICIPALITY', 'Philippines'],
    'Balayan': ['MUNICIPALITY', 'Philippines'],
    'Baliuag': ['MUNICIPALITY', 'Philippines'],
    'Bamban': ['MUNICIPALITY', 'Philippines'],
    'Bangued': ['MUNICIPALITY', 'Philippines'],
    'Banisilan': ['MUNICIPALITY', 'Philippines'],
    'Banna': ['MUNICIPALITY', 'Philippines'],
    'Barili': ['MUNICIPALITY', 'Philippines'],
    'Basud': ['MUNICIPALITY', 'Philippines'],
    'Batan': ['MUNICIPALITY', 'Philippines'],
    'Batac': ['CITY', 'Philippines'],
    'Bay': ['MUNICIPALITY', 'Philippines'],
    'Bayambang': ['MUNICIPALITY', 'Philippines'],
    'Bayawan': ['CITY', 'Philippines'],
    'Baybay': ['CITY', 'Philippines'],
    'Bayombong': ['MUNICIPALITY', 'Philippines'],
    'Binalbagan': ['MUNICIPALITY', 'Philippines'],
    'Binalonan': ['MUNICIPALITY', 'Philippines'],
    'Binmaley': ['MUNICIPALITY', 'Philippines'],
    'Bogo': ['CITY', 'Philippines'],
    'Boliney': ['MUNICIPALITY', 'Philippines'],
    'Bongabon': ['MUNICIPALITY', 'Philippines'],
    'Bontoc': ['MUNICIPALITY', 'Philippines'],
    'Borbon': ['MUNICIPALITY', 'Philippines'],
    'Brookes Point': ['MUNICIPALITY', 'Philippines'],
    'Buadiposo-Buntong': ['MUNICIPALITY', 'Philippines'],
    'Buenavista': ['MUNICIPALITY', 'Philippines'],
    'Bugasong': ['MUNICIPALITY', 'Philippines'],
    'Buguias': ['MUNICIPALITY', 'Philippines'],
    'Bula': ['MUNICIPALITY', 'Philippines'],
    'Bulan': ['MUNICIPALITY', 'Philippines'],
    'Bulusan': ['MUNICIPALITY', 'Philippines'],
    'Buug': ['MUNICIPALITY', 'Philippines'],
    'Cabadbaran': ['CITY', 'Philippines'],
    'Cabagan': ['MUNICIPALITY', 'Philippines'],
    'Cabanatuan': ['CITY', 'Philippines'],
    'Cabatuan': ['MUNICIPALITY', 'Philippines'],
    'Cadiz': ['CITY', 'Philippines'],
    'Cagayan de Oro': ['CITY', 'Philippines'],
    'Cainta': ['MUNICIPALITY', 'Philippines'],
    'Calamba': ['CITY', 'Philippines'],
    'Calapan': ['CITY', 'Philippines'],
    'Calasiao': ['MUNICIPALITY', 'Philippines'],
    'Calauag': ['MUNICIPALITY', 'Philippines'],
    'Calbayog': ['CITY', 'Philippines'],
    'Calinog': ['MUNICIPALITY', 'Philippines'],
    'Calumpit': ['MUNICIPALITY', 'Philippines'],
    'Caloocan': ['CITY', 'Philippines'],
    'Candon': ['CITY', 'Philippines'],
    'Canlaon': ['CITY', 'Philippines'],
    'Carmen': ['MUNICIPALITY', 'Philippines'],
    'Catbalogan': ['CITY', 'Philippines'],
    'Cavite City': ['CITY', 'Philippines'],
    'Cebu City': ['CITY', 'Philippines'],
    'Claveria': ['MUNICIPALITY', 'Philippines'],
    'Cotabato City': ['CITY', 'Philippines'],
    'Cuenca': ['MUNICIPALITY', 'Philippines'],
    'Dagupan': ['CITY', 'Philippines'],
    'Daet': ['MUNICIPALITY', 'Philippines'],
    'Dapitan': ['CITY', 'Philippines'],
    'Dasmariñas': ['CITY', 'Philippines'],
    'Davao City': ['CITY', 'Philippines'],
    'Digos': ['CITY', 'Philippines'],
    'Dipolog': ['CITY', 'Philippines'],
    'Dumaguete': ['CITY', 'Philippines'],
    'El Nido': ['MUNICIPALITY', 'Philippines'],
    'Escalante': ['CITY', 'Philippines'],
    'Gapan': ['CITY', 'Philippines'],
    'General Santos': ['CITY', 'Philippines'],
    'General Trias': ['CITY', 'Philippines'],
    'Gingoog': ['CITY', 'Philippines'],
    'Guihulngan': ['CITY', 'Philippines'],
    'Himamaylan': ['CITY', 'Philippines'],
    'Ilagan': ['CITY', 'Philippines'],
    'Iligan': ['CITY', 'Philippines'],
    'Iloilo City': ['CITY', 'Philippines'],
    'Imus': ['CITY', 'Philippines'],
    'Indang': ['MUNICIPALITY', 'Philippines'],
    'Ipil': ['MUNICIPALITY', 'Philippines'],
    'Iriga': ['CITY', 'Philippines'],
    'Isabela City': ['CITY', 'Philippines'],
    'Jolo': ['MUNICIPALITY', 'Philippines'],
    'Kabankalan': ['CITY', 'Philippines'],
    'Kidapawan': ['CITY', 'Philippines'],
    'Koronadal': ['CITY', 'Philippines'],
    'La Carlota': ['CITY', 'Philippines'],
    'La Trinidad': ['MUNICIPALITY', 'Philippines'],
    'Lamitan': ['CITY', 'Philippines'],
    'Laoag': ['CITY', 'Philippines'],
    'Lapu-Lapu City': ['CITY', 'Philippines'],
    'Legazpi': ['CITY', 'Philippines'],
    'Ligao': ['CITY', 'Philippines'],
    'Lipa': ['CITY', 'Philippines'],
    'Lucena': ['CITY', 'Philippines'],
    'Maasin': ['CITY', 'Philippines'],
    'Mabalacat': ['CITY', 'Philippines'],
    'Makati': ['CITY', 'Philippines'],
    'Malabon': ['CITY', 'Philippines'],
    'Malaybalay': ['CITY', 'Philippines'],
    'Malolos': ['CITY', 'Philippines'],
    'Mandaluyong': ['CITY', 'Philippines'],
    'Mandaue': ['CITY', 'Philippines'],
    'Manila': ['CITY', 'Philippines'],
    'Marawi': ['CITY', 'Philippines'],
    'Marikina': ['CITY', 'Philippines'],
    'Olongapo': ['CITY', 'Philippines'],
    'Ormoc': ['CITY', 'Philippines'],
    'Oroquieta': ['CITY', 'Philippines'],
    'Ozamis': ['CITY', 'Philippines'],
    'Pagadian': ['CITY', 'Philippines'],
    'Palayan': ['CITY', 'Philippines'],
    'Panabo': ['CITY', 'Philippines'],
    'Parañaque': ['CITY', 'Philippines'],
    'Pasay': ['CITY', 'Philippines'],
    'Pasig': ['CITY', 'Philippines'],
    'San Jose': ['CITY', 'Philippines'],
    'San Juan': ['CITY', 'Philippines'],
    'San Pablo': ['CITY', 'Philippines'],
    'Santa Rosa': ['CITY', 'Philippines'],
    'Santiago': ['CITY', 'Philippines'],
    'Silay': ['CITY', 'Philippines'],
    'Sorsogon City': ['CITY', 'Philippines'],
    'Surigao City': ['CITY', 'Philippines'],
    'Tabaco': ['CITY', 'Philippines'],
    'Tacloban': ['CITY', 'Philippines'],
    'Taguig': ['CITY', 'Philippines'],
    'Tagum': ['CITY', 'Philippines'],
    'Talisay': ['CITY', 'Philippines'],
    'Tanauan': ['CITY', 'Philippines'],
    'Tandag': ['CITY', 'Philippines'],
    'Tanjay': ['CITY', 'Philippines'],
    'Tayabas': ['CITY', 'Philippines'],
    'Toledo': ['CITY', 'Philippines'],
    'Trece Martires': ['CITY', 'Philippines'],
    'Tuguegarao': ['CITY', 'Philippines'],
    'Urdaneta': ['CITY', 'Philippines'],
    'Valencia': ['CITY', 'Philippines'],
    'Valenzuela': ['CITY', 'Philippines'],
    'Victorias': ['CITY', 'Philippines'],
    'Vigan': ['CITY', 'Philippines'],
    'Zamboanga City': ['CITY', 'Philippines']
}

CURRENT_INFO_CATEGORIES = {
    "current_weather": [
        "current weather", "lagay ng panahon", "ngayon", "kasalukuyan",
        "weather now", "temperature now", "current temperature", "weather update",
        "pag-ulan", "ulan ngayon", "ulan na", "init ngayon", "bagyo ngayon"
    ],
    "current_forecast": [
        "forecast", "tuloy na lagay ng panahon", "prediction",
        "weather forecast", "next days weather", "upcoming weather", "pag-forecast",
        "panahon sa mga susunod na araw"
    ],
    "current_earthquake": [
        "earthquake now", "lindol", "recent quake", "kasalukuyang lindol",
        "aftershock", "tremor", "lindol ngayon", "lindol sa ph"
    ],
    "current_tsunami": [
        "tsunami alert", "current tsunami", "pag-ula", "storm surge",
        "high tide warning", "wave alert", "babala sa tsunami", "storm surge alert"
    ],
    "current_volcano": [
        "volcano warning", "phivolcs", "bulkang aktibo",
        "volcano alert", "eruption alert", "volcanic activity", "pagputok ng bulkan",
        "phivolcs warning", "active volcano"
    ],
    "current_flood_storm": [
        "flood warning", "storm surge", "flash flood", "gale warning",
        "heavy rain", "ulan na malakas", "river overflow", "babala sa baha",
        "strong wind", "storm warning", "bagyong paparating", "storm surge alert"
    ],
    "current_wildfire": [
        "wildfire", "forest fire", "sunog", "grass fire", "bushfire",
        "fire outbreak", "kalat na sunog", "sunog sa kagubatan"
    ],
    "current_man_made": [
        "accident", "fire incident", "man-made disaster", "traffic incident",
        "chemical spill", "industrial accident", "hazardous event",
        "road accident", "train crash", "factory fire", "oil spill", "panggawaang aksidente"
    ],
    "current_disaster_news": [
        "latest disaster news", "disaster update", "breaking news",
        "recent disasters", "latest calamities", "disaster headlines",
        "news update on disasters", "bagong balita ng sakuna"
    ],
    "disaster_agency_info": [
        "ndrrmc", "pagasa", "phivolcs", "department of disaster", "official",
        "government disaster agencies", "ndrrmc update", "pagasa bulletin",
        "phivolcs advisory", "disaster preparedness officials",
        "chief of ndrrmc", "secretary of disaster", "head of pagasa", "local disaster office"
    ]
}